// 1. Import Area





// 2. Define Area
export async function PUT(){
    // Object.method(actualArgument)
    return Response.json({"impPixelURL":"https://aax-eu.amazon.in/e/xsp/imp?b=RGZn8M6Ac9jvucxEWb6YnacAAAGLKH6Y5AMAAAH_AQBvbm9fdHhuX2JpZDEgICBvbm9fdHhuX2ltcDEgICAtybPj","adIdStr":"591227506056863779","mediaType":"D","creative":"<!DOCTYPE html><html><body><style>.ac{display:block;position:absolute;overflow:hidden;width:19px;height:15px;z-index:9;top:0;right:0;background:url(https://images-eu.ssl-images-amazon.com/images/G/31/da/adchoices/ac-topright-sprite.png)}.ac:hover{width:77px;background-position:-19px 0}.hide{display:none!important}#staticImage{border:0}#ad{position:relative;overflow:hidden;width:244px;height:250px;display:none}</style><div id=\"creative-wrapper\" style=\"width: 100%;height:250px;\">\n  <a id=\"ad\" href=\"https://aax-eu.amazon.in/x/c/RGZn8M6Ac9jvucxEWb6YnacAAAGLKH6Y5AMAAAH_AQBvbm9fdHhuX2JpZDEgICBvbm9fdHhuX2ltcDEgICAtybPj/https://www.amazon.in/dp/B07TBSH8Y8/?aaxitk=3226a3463f00f7c805d3d95b438c8fa6\" target=\"_top\" >\n<img id=\"staticImage\" width=\"100%\" height=\"100%\"><a id=\"logo\"></a><a id=\"aapInfo\" target=\"_blank\" class=\"hide ac\" href=\"https://amazon.in/adprefs/ref=cs_aap_593110666123762542\"></a></div><script>setTimeout(function(){!function(a,e,t){var n,i=/\\.amazon\\.(com|in)(:.*)?$/,c=\"undefined\"!=typeof IS_3P&&IS_3P,o=!1;if(!c)if(n=a,n.SFClient)o=n.SFClient.isOnAmazon();else{try{for(;n!=n.parent;){if(!n.parent.document)throw new Error(\"cross-domain exception\");n=n.parent}}catch(r){}try{o=n.SFClient?n.SFClient.isOnAmazon():i.test(n.location.host)}catch(r){}}var s=!c&&!o;e.ad={aid:\"591227506056863779\",cid:\"593110666123762542\",w:244,h:250,template:\"Image - IN-1.49\"},a.aanResponse={adId:e.ad.aid,creativeId:e.ad.cid,adNetwork:\"pda\",shazamStage:\"prod\",shazamId:\"76759221\"};try{t&&t.ad_utils&&t.ad_utils.expand_ad(frameElement)}catch(r){}var d=function(a){return e.getElementById(a)},m=function(a,e,t){a.href=e,a.target=t?\"_blank\":\"_top\"},p=function(a,e){return a.className.match(new RegExp(\"(\\\\s|^)\"+e+\"(\\\\s|$)\"))},f=function(a,e){p(a,e)||(a.className+=\" \"+e)},l=function(a,e){if(p(a,e)){var t=new RegExp(\"(\\\\s|^)\"+e+\"(\\\\s|$)\");a.className=a.className.replace(t,\" \")}},u=function(a){l(a,\"hide\")},h=d(\"aapInfo\"),g=d(\"ad\"),I=\"https://m.media-amazon.com/images/I/4128RDK8r+L.jpg\",S=d(\"staticImage\");I&&(S.src=I,g.style.display=\"block\");var _;c&&f(g,\"aap\"),(c||s)&&(g.target=\"_blank\"),h&&c&&u(h),_&&m(h,\"https://amazon.in/adprefs\",!0);var y=a.SFClient;if(y&&\"function\"==typeof y.changeSize)try{y.changeSize(\"244px\",\"250px\")}catch(r){}}(window,document,parent)},0);</script>\n</body></html><!-- creativeModDate = 1697029672000 -->","creativeId":593110666123762542,"aaxMeasurementTrackers":{"contains3P":"false","html":""},"adId":591227506056863779,"instrPixelURL":"https://aax-eu.amazon.in/x/px/RGZn8M6Ac9jvucxEWb6YnacAAAGLKH6Y5AMAAAH_AQBvbm9fdHhuX2JpZDEgICBvbm9fdHhuX2ltcDEgICAtybPj/","creativeIdStr":"593110666123762542","programId":1002,"status":"ok"}
);
}